services:
  marimo-test:
    image: sbtscala/scala-sbt:eclipse-temurin-17.0.4_1.7.1_3.2.0
    working_dir: /app
    volumes:
      - ./:/app
    command: sbt run Main
    ports:
      - "8080:8080"

volumes:
  pgdata: