apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: marimo-controller-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "delete"]
